version: "3"
services:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ndungu
      - MONGO_INITDB_ROOT_PASSWORD=ndungu11
  nginx:
    ports: 
      - "3000:80"
  blog-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ndungu
      - MONGO_PASSWORD=ndungu11
      - SESSION_SECRET=ndungu11
    command: npm run dev

    