version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  blog-app:
    build: .
    # ports:
    #  - "3000:3000"
    environment:
     - PORT=3000
    depends_on:
      - mongodb
      # - redis

  mongodb:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=ndungu
    #   - MONGO_INITDB_ROOT_PASSWORD=ndungu11
    volumes:
      - mongod:/data/db
    
  redis-server:
    image: redis


volumes:
  mongod: