version: "3"
services:
  blogApp:
    build:
      context: .
      args:
       - NODE_ENV: development
      volumes:
        - ./:/app:ro
        - /app/node_modules
      environment:
        - NODE_ENV: development
        - MONGO_USER: ndungu
        - MONGO_PASSWORD: ndungu11
      command: npm run dev
      
    