version: "3"
services:
  blog-app:
    build: .
    ports:
     - "3000:3000"
    environment:
     - PORT=3000
    depends_on:
      - mongodb
      # - redis

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ndungu
      - MONGO_INITDB_ROOT_PASSWORD=ndungu11
    volumes:
      - mongod:/data/db
    
  redis-server:
    image: redis


volumes:
  mongod: