version: "3"
services:
  nginx:
    ports: 
      - "80:80"
  blog-app:
    build:
      context: .
      args:
       - NODE_ENV: production
    environment:
      NODE_ENV=production
    command: node app.js